spring.application.name=practica4

server.port=8090

# BD en memoria (se destruye al reiniciar)
spring.datasource.url=jdbc:h2:mem:ejemplo_db
# BD persistente en fichero
# spring.datasource.url=jdbc:h2:file:./src/main/resources/database
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver
# Consola de administración H2
spring.h2.console.enabled=true
# Acceso: http://localhost:8090/h2-console/login.do

# Inserccion de datos en memoria con un data.sql
spring.jpa.defer-datasource-initialization=true 