CREATE TABLE ENVIO(
    id LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_envio VARCHAR(50) UNIQUE,
    solicitante VARCHAR(100),
    direccion_origen VARCHAR(100),
    direccion_destino VARCHAR(100),
    datos_mercancia VARCHAR(100),
    datos_envio VARCHAR(100));